services:
  app:
    image: board-game:latest
    build:
      context: ./board-game-store-service
      dockerfile: Dockerfile
    container_name: board-game-store-service
    ports:
      - "8080:8080"
