spring:
  application:
    name: board-game-store
  r2dbc:
    url: r2dbc:postgresql://db:5432/occupation-data
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

server:
  port: 13000
